{
 "title": "CM1200 & UDM SE Internet Uptime Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "WAN Connection Resets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "resets(unifi_site_uptime_seconds[5m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDM WAN Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "unifi_site_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet Loss Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - probe_success{job=\"icmp_probes\", instance!=\"192.168.100.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cable Modem SNR (Min/Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 23 },
   "targets": [
    { "expr": "min(netgear_downstream_snr)", "legendFormat": "__auto" },
    { "expr": "avg(netgear_downstream_snr)", "legendFormat": "__auto" }
   ]
  }
 ]
}